stages:
  - docker
  - deploy

# -----------------------------
# 1. Build & Push to Docker Hub
# -----------------------------
docker-build-push:
  stage: docker
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_IMAGE: $DOCKER_HUB_USERNAME/$DOCKER_HUB_REPO
    DOCKER_TAG: $CI_COMMIT_SHORT_SHA
  before_script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
    - docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:latest
  only:
    - main

# -----------------------------
# 2. Deploy to Server
# -----------------------------
deploy:
  stage: deploy
  image: alpine:latest
  needs: ["docker-build-push"]
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  script:
    - ssh -p ${SSH_PORT:-22} $DEPLOY_USER@$DEPLOY_HOST "
        docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD &&
        docker pull $DOCKER_IMAGE:$DOCKER_TAG &&
        docker stop ${CONTAINER_NAME:-my-api} || true &&
        docker rm ${CONTAINER_NAME:-my-api} || true &&
        docker run -d --name ${CONTAINER_NAME:-my-api} -p ${HOST_PORT:-3000}:${CONTAINER_PORT:-3000} $DOCKER_IMAGE:$DOCKER_TAG
      "
  only:
    - main
