services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    services:
  mongo:
    image: mongo
  app:
    build: .
    depends_on:
      - mongo
